global:
  scrape_interval: 15s

  external_labels:
    monitor: "go-backend"

scrape_configs:
  - job_name: "rides"
    scrape_interval: 3s

    static_configs:
      - targets: ["host.docker.internal:8080"]
