basePath: /
definitions:
  handlers.RideRequest:
    properties:
      user_id:
        type: string
      vehicle_id:
        type: string
    type: object
  rides.Ride:
    properties:
      created_at:
        type: string
      finished:
        type: boolean
      id:
        type: integer
      price:
        type: integer
      updated_at:
        type: string
      user_id:
        type: string
      vehicle_id:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: andres@reveronmolina.me
    name: systemallica
    url: http://www.andres.reveronmolina.me
  description: This is a basic Rides API using Chi and go-rel.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Rides Swagger API
paths:
  /rides:
    post:
      consumes:
      - application/json
      description: create ride
      parameters:
      - description: Ride request parameters
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/handlers.RideRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/rides.Ride'
      summary: starts a ride.
      tags:
      - rides
  /rides/:id/finish:
    post:
      consumes:
      - application/json
      description: finish ride
      parameters:
      - description: Ride ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rides.Ride'
      summary: finishes the ride that matches the given ID.
      tags:
      - rides
schemes:
- http
- https
swagger: "2.0"
